In [1]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

# Strip cases

In [3]:
y="19M"
a=y.rstrip("M")
int(a)

19

In [4]:
d1={"id": 101,"name": "India","age": 200,"city": "Delhi"}
print(d1)


{'id': 101, 'name': 'India', 'age': 200, 'city': 'Delhi'}


In [4]:
import numpy as np

In [5]:
a=[1,3,5,6]
b=[4,5,6,7]
arr1=np.array(a)
arr2=np.array(b)

In [7]:
arr2

array([4, 5, 6, 7])

In [6]:
arr1 * arr2

array([ 4, 15, 30, 42])

In [9]:
arr1.ndim

1

In [7]:
arr1.shape

(4,)

In [11]:
arr1.dtype

dtype('int64')

In [14]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr3.ndim

2

In [16]:
arr3.shape

(3, 3)

In [18]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [24]:
np.random.randint(10,100,12).reshape(4,3)

array([[97, 81, 82],
       [96, 70, 88],
       [77, 93, 95],
       [64, 99, 71]], dtype=int32)

In [25]:
r=45.7
np.floor(r)

np.float64(45.0)

In [28]:
np.ceil(r)

np.float64(46.0)

In [31]:
import pandas as pd

In [32]:
renewable_sources = ['Solar', 'Wind', 'Hydropower', 'Geothermal', 'Biomass']

data = {
    "Project":['Solar Farm', 'Wind Turbine', 'Hydropower', 'Solar Roof', 'Geothermal Plant'],
    "Technology":['Solar', 'Wind', 'Hydro', 'Solar', 'Geothermal'],
    "Capacity (MW)":[150, 300, 200, 50, 100],
    "Cost (Millions $)":[200, 400, 350, 100, 250],
    "Location":["California", "Texas", "Washington", "Nevada", "Chicago"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}


In [34]:
#Create a pandas series for renewable energy sources
renewable_series=pd.Series(renewable_sources)
print('Renewable energy sources are:')
print(renewable_series)

Renewable energy sources are:
0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [35]:
#create a Dataframe for green tech projects
df=pd.DataFrame(data)
print("Green Technologies projects Dataframe:")
print(df)

Green Technologies projects Dataframe:
            Project  Technology  Capacity (MW)  Cost (Millions $)    Location  \
0        Solar Farm       Solar            150                200  California   
1      Wind Turbine        Wind            300                400       Texas   
2        Hydropower       Hydro            200                350  Washington   
3        Solar Roof       Solar             50                100      Nevada   
4  Geothermal Plant  Geothermal            100                250     Chicago   

   Completion Year  
0             2023  
1             2024  
2             2022  
3             2025  
4             2023  


In [36]:
df['Project']

0          Solar Farm
1        Wind Turbine
2          Hydropower
3          Solar Roof
4    Geothermal Plant
Name: Project, dtype: object

In [37]:
print(df['Project'])

0          Solar Farm
1        Wind Turbine
2          Hydropower
3          Solar Roof
4    Geothermal Plant
Name: Project, dtype: object


In [39]:
df['Location']

0    California
1         Texas
2    Washington
3        Nevada
4       Chicago
Name: Location, dtype: object

In [43]:
#want to print high capacity projects(>100MW)
hcp = df[df['Capacity (MW)']>100]
hcp

Project Technology  Capacity (MW)  Cost (Millions $)    Location  \
0    Solar Farm      Solar            150                200  California   
1  Wind Turbine       Wind            300                400       Texas   
2    Hydropower      Hydro            200                350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [44]:
df['Capacity (MW)']>100

0     True
1     True
2     True
3    False
4    False
Name: Capacity (MW), dtype: bool

In [49]:
#add new col
df["Cost per MW"] = df["Cost (Millions $)"] / df['Capacity (MW)']
df

Project  Technology  Capacity (MW)  Cost (Millions $)    Location  \
0        Solar Farm       Solar            150                200  California   
1      Wind Turbine        Wind            300                400       Texas   
2        Hydropower       Hydro            200                350  Washington   
3        Solar Roof       Solar             50                100      Nevada   
4  Geothermal Plant  Geothermal            100                250     Chicago   

   Completion Year  Cost per MW  
0             2023     1.333333  
1             2024     1.333333  
2             2022     1.750000  
3             2025     2.000000  
4             2023     2.500000

In [53]:
#aggregation 
total_capacity = df['Capacity (MW)'].sum()
total_cost = df['Cost (Millions $)'].sum()
print("The total Capacity of all the projects are:",total_capacity)
print("The total cost of the projects:",total_cost)

The total Capacity of all the projects are: 800
The total cost of the projects: 1300


In [54]:
#Groupimg of data
grouped_data = df.groupby("Technology")["Capacity (MW)"].sum()
grouped_data

Technology
Geothermal    100
Hydro         200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64

## DAy3:Numpy

In [13]:
import numpy as np

energy_consumption=np.array([1200, 3400, 2900, 1800, 2500])
print("Energy Consumptionin mwh for different energy sources:")
energy_consumption

Energy Consumptionin mwh for different energy sources:


array([1200, 3400, 2900, 1800, 2500])

In [14]:
# Calculate the total energy consumption
total_consumption = np.sum(energy_consumption)
print(f'The total energy consumption is {total_consumption} in mwh')

The total energy consumption is 11800 in mwh


In [15]:
#Calculate the mean energy consumption 
mean_consumption=np.mean(energy_consumption)
print(f"The mean energy consumption is {mean_consumption} MWh")

The mean energy consumption is 2360.0 MWh


In [16]:
# Calculate the standard deviation of energy consumption 
std_ec=np.std(energy_consumption)
std_ec

np.float64(781.2809993849844)

In [17]:
print(f"The standard deviation of energy consumption {std_ec} MWh")

The standard deviation of energy consumption 781.2809993849844 MWh


In [17]:
# Reshape the array
reshaped_array=energy_consumption.reshape((5,1))
print("Reshaped array is:")
print(reshaped_array)

Reshaped array is:
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]


## Data preprocessing

In [18]:
import pandas as pd
import numpy as np

# Sample data with missing values
data = {
    "Energy Source": ['Solar', 'Wind', 'Hydropower', 'Geothermal', 'Biomass', 'Nuclear'],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (millions $)": [200, 400, np.nan, 150, 250, np.nan]
}


In [19]:
# Create a DataFrame
df = pd.DataFrame(data)
print(df)

  Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                       NaN              400.0
2    Hydropower                    2900.0                NaN
3    Geothermal                       NaN              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0                NaN


## Handling the Missing Value:
Rmoving(drop)mv


impute(fill)mv-mean

In [20]:
#Remove rows with missing values 
cleaned_df= df.dropna()
cleaned_df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
4       Biomass                    2500.0              250.0

## Imputation-to add or fill
.with mean

. forward/backward filling

In [21]:
# Impute missing values with the mean for energy consumption
df["Energy Consumption (MWh)"].fillna(df['Energy Consumption (MWh)']. mean(), inplace=True)
df["Cost (millions $)"].fillna(df["Cost (millions $)"].mean(), inplace=True)

df

C:\Users\91810\AppData\Local\Temp\ipykernel_16220\1149159332.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Energy Consumption (MWh)"].fillna(df['Energy Consumption (MWh)']. mean(), inplace=True)
C:\Users\91810\AppData\Local\Temp\ipykernel_16220\1149159332.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are settin

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                    2450.0              400.0
2    Hydropower                    2900.0              250.0
3    Geothermal                    2450.0              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0              250.0

In [22]:
# Forward filing missing values
ff_df = df.fillna(method="ffill")
ff_df

C:\Users\91810\AppData\Local\Temp\ipykernel_16220\1475923195.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ff_df = df.fillna(method="ffill")


Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                    2450.0              400.0
2    Hydropower                    2900.0              250.0
3    Geothermal                    2450.0              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0              250.0

In [23]:
# Data Preprocessing - Normalization
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[["Energy Consumption (MWh)", "Cost (millions $)"]] = scaler.fit_transform(df[["Energy Consumption (MWh)", "Cost (millions $)"]])

df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                     0.000                0.2
1          Wind                     0.625                1.0
2    Hydropower                     0.850                0.4
3    Geothermal                     0.625                0.0
4       Biomass                     0.650                0.4
5       Nuclear                     1.000                0.4

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['Energy Consumption (MWh)', 'Cost (millions $)']] = scaler.fit_transform(
    df[['Energy Consumption (MWh)', 'Cost (millions $)']])
df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar             -2.005893e+00      -6.546537e-01
1          Wind              3.563181e-16       1.963961e+00
2    Hydropower              7.221213e-01       1.817029e-16
3    Geothermal              3.563181e-16      -1.309307e+00
4       Biomass              8.023570e-02       1.817029e-16
5       Nuclear              1.203536e+00       1.817029e-16

In [30]:
ohe_df = pd.get_dummies(df, columns=["Energy Source"])
print(ohe_df)

   Energy Consumption (MWh)  Cost (millions $)  Energy Source_Biomass  \
0             -2.005893e+00      -6.546537e-01                  False   
1              3.563181e-16       1.963961e+00                  False   
2              7.221213e-01       1.817029e-16                  False   
3              3.563181e-16      -1.309307e+00                  False   
4              8.023570e-02       1.817029e-16                   True   
5              1.203536e+00       1.817029e-16                  False   

   Energy Source_Geothermal  Energy Source_Hydropower  Energy Source_Nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5       

In [33]:
# Feature engineering
ohe_df["Consumption per Million $"] = ohe_df['Energy Consumption (MWh)'] / ohe_df['Cost (millions $)']

ohe_df

Energy Consumption (MWh)  Cost (millions $)  Energy Source_Biomass  \
0             -2.005893e+00      -6.546537e-01                  False   
1              3.563181e-16       1.963961e+00                  False   
2              7.221213e-01       1.817029e-16                  False   
3              3.563181e-16      -1.309307e+00                  False   
4              8.023570e-02       1.817029e-16                   True   
5              1.203536e+00       1.817029e-16                  False   

   Energy Source_Geothermal  Energy Source_Hydropower  Energy Source_Nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5                     False                     False                   True   

   Energy Source_Solar  Energy Source_Wind  Consumption per Million $  
0                 True               False               3.064052e+00  
1                False                True               1.814283e-16  
2                False               False               3.974187e+15  
3                False               False              -2.721424e-16  
4                False               False               4.415764e+14  
5                False               False               6.623646e+15